// Generated by CoffeeScript 1.8.0
var rewire, util;

util = require('util');

rewire = require('rewire');

describe('site module', function() {
  var site, testId, unknownSite;
  site = rewire('../lib/site.js');
  unknownSite = 'www.example.com';
  testId = 'testid0000';
  describe('generate product url', function() {
    var called, makeCalledFalse, makeCalledTrue, restore;
    called = false;
    makeCalledTrue = function() {
      called = true;
    };
    makeCalledFalse = function() {
      called = false;
    };
    restore = null;
    beforeEach(function() {
      makeCalledFalse();
      restore = site.__set__({
        siteNotSupportHandler: function() {}
      });
    });
    afterEach(function() {
      return restore();
    });
    it('should generate amazon cn product url', function() {
      var url;
      url = util.format('http://www.amazon.cn/dp/%s', testId);
      site.generateProductUrl(testId, 'www.amazon.cn').should.equal(url);
    });
    it('should generate amazon com product url', function() {
      var url;
      url = util.format('http://www.amazon.com/dp/%s', testId);
      site.generateProductUrl(testId, 'www.amazon.com').should.equal(url);
    });
    it('should generate amazon jp product url', function() {
      var url;
      url = util.format('http://www.amazon.co.jp/dp/%s', testId);
      site.generateProductUrl(testId, 'www.amazon.co.jp').should.equal(url);
    });
    it('should generate jingdong product url', function() {
      var url;
      url = util.format('http://wap.jd.com/product/%s.html', testId);
      site.generateProductUrl(testId, 'www.jd.com').should.equal(url);
    });
    it('should route to site not support handler', function() {
      site.__set__('siteNotSupportHandler', makeCalledTrue);
      site.generateProductUrl(testId, unknownSite);
      called.should.be["true"];
    });
  });
  describe('get site encoding', function() {
    var called, makeCalledFalse, makeCalledTrue, restore;
    called = false;
    makeCalledTrue = function() {
      called = true;
    };
    makeCalledFalse = function() {
      called = false;
    };
    restore = null;
    beforeEach(function() {
      makeCalledFalse();
      restore = site.__set__({
        siteNotSupportHandler: function() {}
      });
    });
    afterEach(function() {
      return restore();
    });
    it('should return utf8 on all amazon sites', function() {
      site.getSiteEncoding('www.amazon.cn').should.equal('utf8');
      site.getSiteEncoding('www.amazon.com').should.equal('utf8');
      site.getSiteEncoding('www.amazon.co.jp').should.equal('utf8');
    });
    it('should return utf8 on jingdong site', function() {
      site.getSiteEncoding('www.jd.com').should.equal('utf8');
    });
    it('should route to site not support handler', function() {
      site.__set__('siteNotSupportHandler', makeCalledTrue);
      site.getSiteEncoding(unknownSite);
      called.should.be["true"];
    });
  });
  describe('url to site', function() {
    var called, makeCalledFalse, makeCalledTrue, restore;
    called = false;
    makeCalledTrue = function() {
      called = true;
    };
    makeCalledFalse = function() {
      called = false;
    };
    restore = null;
    beforeEach(function() {
      makeCalledFalse();
      restore = site.__set__({
        siteNotSupportHandler: function() {}
      });
    });
    afterEach(function() {
      return restore();
    });
    it('should return amazon cn site url', function() {
      site.urlToSite('www.amazon.cn').should.equal('www.amazon.cn');
      site.urlToSite('www.amazon.cn/dp/foo').should.equal('www.amazon.cn');
    });
    it('should return amazon com site url', function() {
      site.urlToSite('www.amazon.com').should.equal('www.amazon.com');
      site.urlToSite('www.amazon.com/dp/foo').should.equal('www.amazon.com');
    });
    it('should return amazon jp site url', function() {
      site.urlToSite('www.amazon.co.jp').should.equal('www.amazon.co.jp');
      site.urlToSite('www.amazon.co.jp/dp/bar').should.equal('www.amazon.co.jp');
    });
    it('should return jingdong site url', function() {
      site.urlToSite('www.jd.com').should.equal('www.jd.com');
      site.urlToSite('item.jd.com/example.html').should.equal('www.jd.com');
    });
    it('should route to url not support handler', function() {
      site.__set__('urlNotSupportHandler', makeCalledTrue);
      site.urlToSite(unknownSite);
      called.should.be["true"];
    });
  });
});
