// Generated by CoffeeScript 1.8.0
var argvParser, fs, launch, launchMonitor, logger, path, verifyUserTokens;

path = require("path");

fs = require("fs");

global.rootRequire = function(name) {
  return require(path.join(__dirname, name));
};

logger = require('winston');

logger.add(logger.transports.File, {
  filename: '/tmp/ebuy_monitor.log'
});

global.logger = logger;

verifyUserTokens = function(callback) {
  var accessTokens, request, userServiceUrl, verifyToken;
  request = require("request");
  userServiceUrl = rootRequire("src/config.js").userServiceUrl;
  accessTokens = rootRequire("src/config.js").accounts.map(function(account) {
    return account.accessToken;
  });
  verifyToken = function(token) {
    var makeVerifyOK, options, printSuccess, shortToken;
    options = {
      url: userServiceUrl,
      auth: {
        user: token
      }
    };
    shortToken = token.slice(0, 7);
    makeVerifyOK = function() {
      var counter;
      counter = accessTokens.length;
      return function() {
        counter -= 1;
        logger.info("token %s verify ok", shortToken);
        if (counter === 0) {
          logger.info("all token verify done.");
          callback();
        }
      };
    };
    printSuccess = makeVerifyOK();
    request.get(options, function(err, res, body) {
      if (!err && res.statusCode === 200) {
        return printSuccess();
      } else {
        logger.warn("token %s verify failed", shortToken);
        logger.warn("error: %s", err);
        logger.warn("status code: %s", res.statusCode);
        logger.warn("failure message: %s", body);
        logger.error("account access token verify caught failed, exit.");
        process.exit();
      }
    });
  };
  logger.info("access token verifying ...");
  accessTokens.map(verifyToken);
};

launchMonitor = function() {
  var async, asyncParallelRequests, monitorInterval, monitorSeeds, seed, visit, visitor;
  seed = rootRequire("src/seed.js");
  monitorSeeds = JSON.parse(fs.readFileSync(path.join(__dirname, "product.json"))).map(function(item) {
    return seed(item);
  });
  async = require("async");
  visitor = rootRequire("src/visitor.js");
  visit = function(seed) {
    var v;
    v = visitor.select(seed);
    v.visit();
  };
  asyncParallelRequests = function() {
    async.map(monitorSeeds, visit, function(err, results) {
      logger.error(err);
    });
  };
  monitorInterval = rootRequire("src/config.js").monitorInterval;
  asyncParallelRequests();
  return setInterval(asyncParallelRequests, monitorInterval);
};

launch = function() {
  verifyUserTokens(launchMonitor);
};

argvParser = rootRequire("src/argv_parser.js");

argvParser.parse(process.argv.slice(2), launch);
