// Generated by CoffeeScript 1.8.0
var argvParser, fs, launch, launchMonitor, logger, path, verifyUserTokens;

fs = require("fs");

path = require("path");

global.rootRequire = function(name) {
  return require(path.join(__dirname, name));
};

logger = require('winston');

logger.add(logger.transports.File, {
  filename: '/tmp/ebuy_monitor.log'
});

global.logger = logger;

verifyUserTokens = function(callback) {
  var accessTokens, request, userServiceUrl, verifyToken;
  request = require("request");
  userServiceUrl = rootRequire("src/config.js").userServiceUrl;
  accessTokens = rootRequire("src/config.js").accounts.map(function(account) {
    return account.accessToken;
  });
  verifyToken = function(token) {
    var makeVerifyOK, options, printSuccess, shortToken;
    options = {
      url: userServiceUrl,
      auth: {
        user: token
      }
    };
    shortToken = token.slice(0, 7);
    makeVerifyOK = function() {
      var counter;
      counter = accessTokens.length;
      return function() {
        counter -= 1;
        logger.info("token %s verify ok", shortToken);
        if (counter === 0) {
          logger.info("all token verify done.");
          callback();
        }
      };
    };
    printSuccess = makeVerifyOK();
    request.get(options, function(err, res, body) {
      if (!err && res.statusCode === 200) {
        return printSuccess();
      } else if (err) {
        logger.error("token %s verify caught request error.", shortToken);
        logger.error("error: %s", err);
        logger.error("account access token verify caught failed, exit.");
        process.exit();
      } else {
        logger.warn("token %s verify response error", shortToken);
        logger.warn("status code: %s", res.statusCode);
        logger.warn("error message: %s", body);
      }
    });
  };
  logger.info("access token verifying ...");
  accessTokens.map(verifyToken);
};

launchMonitor = function() {
  var async, asyncParallelRequests, client, config, db, delaySeed, iterate, monitorInterval, pushQueueKey, seed, seeds, visit, visitor;
  seed = rootRequire("src/seed.js");
  seeds = JSON.parse(fs.readFileSync(path.join(__dirname, "product.json"))).map(function(item) {
    return seed(item);
  });
  delaySeed = function(id, site) {
    var resendDelay;
    resendDelay = rootRequire("src/config.js").resendDelay;
    seeds = seeds.filter(function(elt) {
      return elt.id !== id || elt.site !== site;
    });
    seeds.filter(function(elt) {
      return elt.id === id && elt.site === site;
    }).forEach(function(elt) {
      var pushSeedBack;
      pushSeedBack = function() {
        seeds.push(elt);
      };
      logger.info("product id %s site %s delayed.", elt.id, elt.site);
      setTimeout(pushSeedBack, resendDelay);
    });
  };
  async = require("async");
  visitor = rootRequire("src/visitor.js");
  monitorInterval = rootRequire("src/config.js").monitorInterval;
  visit = function(seed) {
    var v;
    v = visitor.select(seed);
    v.visit();
  };
  asyncParallelRequests = function() {
    async.map(seeds, visit, function(err, results) {
      logger.error(err);
    });
  };
  config = rootRequire("src/config.js");
  pushQueueKey = config.redisPushQueueKey;
  db = rootRequire("src/db_client.js");
  client = db.newClient();
  iterate = function() {
    var iter;
    iter = function() {
      var item;
      item = JSON.parse(client.rpop(pushQueueKey));
      if (item.id && item.site) {
        delaySeed(item.id, item.site);
        iter();
      }
    };
    iter();
    asyncParallelRequests();
  };
  asyncParallelRequests();
  return setInterval(iterate, monitorInterval);
};

launch = function() {
  verifyUserTokens(launchMonitor);
};

argvParser = rootRequire("src/argv_parser.js");

argvParser.parse(process.argv.slice(2), launch);
