// Generated by CoffeeScript 1.8.0
var config, fs, logDirectory, logFile, logger, path;

path = require('path');

fs = require('fs');

config = JSON.parse(fs.readFileSync(path.join(__dirname, '../config.json'), 'utf8'));

logDirectory = './log';

logFile = path.join(logDirectory, config.logFileName);

!fs.existsSync(logDirectory) && fs.mkdirSync(logDirectory);

logger = require('winston');

logger.add(logger.transports.File, {
  filename: logFile,
  level: config.loggerLevel
});

global.logger = logger;

module.exports = config;
