// Generated by CoffeeScript 1.8.0
var client, config, redis, redisRecordDBIndex;

redis = require('redis');

config = require('./config.js');

redisRecordDBIndex = config.redisRecordDBIndex;

client = null;

module.exports.createClient = function() {
  client = redis.createClient(config.redisPort, config.redisHost);
  client.select(redisRecordDBIndex, function(err, res) {
    if (err) {
      logger.error('redis select %s failed', redisRecordDBIndex);
      throw err;
    } else {
      logger.debug('redis select %s %s', redisRecordDBIndex, res);
    }
  });
  client.on('error', function(err) {
    logger.error('visitor record client caught error');
    throw err;
  });
  logger.debug('redis record client connect success');
};

module.exports.getClient = function() {
  if (client) {
    return client;
  } else {
    logger.debug('database client should be created just after monitor launched');
    throw new Error('client not initialized');
  }
};
