// Generated by CoffeeScript 1.8.0
var db, monitor;

db = require('./db.js');

monitor = require('./monitor.js');

module.exports.launch = function() {
  require('./argv_parser.js').parse(process.argv.slice(2), function() {
    process.on('SIGINT', function() {
      logger.info('Caught SIGINT, try teardown redis and mongodb instance');
      db.stopDBService();
      setTimeout((function() {
        return process.exit(1);
      }), 1000);
    });
    db.startDBService();
    setTimeout((function() {
      db.connectRedis();
      db.clearQueue();
      db.connectMongoDB();
      monitor.createMonitor().start();
    }), 1000);
  });
};
