// Generated by CoffeeScript 1.8.0
var db, monitor;

db = require('./db_client.js');

monitor = require('./monitor.js');

module.exports.launch = function() {
  require('./argv_parser.js').parse(process.argv.slice(2), function() {
    var m;
    db.createClient();
    m = monitor.createMonitor().start();
  });
};
