// Generated by CoffeeScript 1.8.0
var AmazonCNVisitor, AmazonJPVisitor, AmazonUSVisitor, JingDongVisitor, MANDATORY_BASE_FIELDS, MANDATORY_EXPAND_FIELDS, Visitor, config, createParser, db, iconv, invalidSiteHandler, request, requestErrorHandler, responseErrorHandler, s, util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

request = require('request');

util = require('util');

iconv = require('iconv-lite');

config = require('./config.js');

s = require('./seed.js');

MANDATORY_EXPAND_FIELDS = s.MANDATORY_EXPAND_FIELDS;

MANDATORY_BASE_FIELDS = s.MANDATORY_BASE_FIELDS;

createParser = require('./page_parser.js').createParser;

db = require('./db.js');

Visitor = (function() {
  function Visitor(seed) {
    this.seed = seed;
    this.client = db.getClient();
  }

  Visitor.prototype.visit = function() {
    var self;
    self = this;
    request.get({
      url: self.seed.url,
      encoding: null
    }, function(err, res, body) {
      if (!err) {
        if (res.statusCode === 200) {
          self.processPage(iconv.decode(new Buffer(body), self.seed.encoding));
        } else {
          responseErrorHandler(self.constructor, res, body);
        }
      } else {
        requestErrorHandler(self.constructor, self.seed.url, err);
      }
    });
  };

  Visitor.prototype.processPage = function(html) {
    var date, delayDebugMsg, delayMsg, result;
    date = new Date();
    result = this.parsePage(html);
    if (this.seed.verdict(result)) {
      delayDebugMsg = 'push and delay ';
      MANDATORY_BASE_FIELDS.map(function(field) {
        delayDebugMsg += util.format('%s %s', field, result[field]);
      });
      logger.debug(delayDebugMsg);
      delayMsg = {};
      MANDATORY_BASE_FIELDS.map(function(field) {
        delayMsg[field] = result[field];
      });
      this.client.lpush(config.redisDelayQueueKey, JSON.stringify(delayMsg));
      this.client.lpush(config.redisPushQueueKey, JSON.stringify(result));
    }
    result.date = date.toUTCString();
    this.client.lpush(config.redisHistoryKey, JSON.stringify(result));
  };

  Visitor.prototype.parsePage = function(html) {
    var field, mountField, result, self, val, _ref;
    self = this;
    result = {};
    mountField = function(field) {
      result[field] = self.seed[field];
    };
    MANDATORY_BASE_FIELDS.map(mountField);
    MANDATORY_EXPAND_FIELDS.map(mountField);
    _ref = createParser(this.seed.site).parse(html);
    for (field in _ref) {
      val = _ref[field];
      result[field] = val;
    }
    logger.debug(result);
    return result;
  };

  return Visitor;

})();

AmazonCNVisitor = (function(_super) {
  __extends(AmazonCNVisitor, _super);

  function AmazonCNVisitor() {
    return AmazonCNVisitor.__super__.constructor.apply(this, arguments);
  }

  return AmazonCNVisitor;

})(Visitor);

AmazonUSVisitor = (function(_super) {
  __extends(AmazonUSVisitor, _super);

  function AmazonUSVisitor() {
    return AmazonUSVisitor.__super__.constructor.apply(this, arguments);
  }

  return AmazonUSVisitor;

})(Visitor);

AmazonJPVisitor = (function(_super) {
  __extends(AmazonJPVisitor, _super);

  function AmazonJPVisitor() {
    return AmazonJPVisitor.__super__.constructor.apply(this, arguments);
  }

  return AmazonJPVisitor;

})(Visitor);

JingDongVisitor = (function(_super) {
  __extends(JingDongVisitor, _super);

  function JingDongVisitor() {
    return JingDongVisitor.__super__.constructor.apply(this, arguments);
  }

  return JingDongVisitor;

})(Visitor);

requestErrorHandler = function(visitor, url, err) {
  logger.error('%s get request failed', visitor);
  logger.error('%s url: %s', visitor, url);
  logger.error('%s err: %s', visitor, err.message);
  throw err;
};

responseErrorHandler = function(visitor, res, body) {
  logger.error('%s response error', visitor);
  logger.error('%s url: %s', visitor, res.url);
  logger.error('%s status code: %s', visitor, res.statusCode);
  logger.error('%s body: %s', visitor, body);
};

invalidSiteHandler = function(site) {
  logger.error('no available visitor for site %s', site);
  throw new Error('invalid data error, no available visitor for invalid site');
};

exports.createVisitor = function(seed) {
  var visitor;
  visitor = (function() {
    switch (seed.site) {
      case 'www.amazon.com':
        return new AmazonUSVisitor(seed);
      case 'www.amazon.cn':
        return new AmazonCNVisitor(seed);
      case 'www.amazon.co.jp':
        return new AmazonJPVisitor(seed);
      case 'www.jd.com':
        return new JingDongVisitor(seed);
      default:
        return invalidSiteHandler(seed.site);
    }
  })();
  return visitor;
};

module.exports = exports;
