// Generated by CoffeeScript 1.8.0
var availableSites, cheerio, monitorItems, request;

request = require("request");

cheerio = require("cheerio");

availableSites = {
  amazonCN: "www.amazon.cn",
  amazonUS: "www.amazon.com"
};

monitorItems = [
  {
    id: "B00K68MONW",
    site: availableSites.amazonCN,
    category: "laptop",
    url: "http://www.amazon.cn/dp/B00K68MONW"
  }, {
    id: "B00MFC4UGG",
    site: availableSites.amazonCN,
    category: "laptop",
    url: "http://www.amazon.cn/dp/B00MFC4UGG"
  }, {
    id: "B00MFEI7RW",
    site: availableSites.amazonCN,
    category: "laptop",
    url: "http://www.amazon.cn/dp/B00MFEI7RW"
  }
];

monitorItems.map(function(item) {
  request(item.url, function(error, response, body) {
    var $;
    if ((!error) && response.statusCode === 200) {
      $ = cheerio.load(body);
      $('#priceblock_ourprice').each(function() {
        console.log('%s', $(this).text());
      });
    }
  });
});
