// Generated by CoffeeScript 1.8.0
var cheerio, monitorItems, request, seed;

request = require("request");

cheerio = require("cheerio");

seed = require("./seed.js");

monitorItems = [seed("B00K68MONW", "www.amazon.cn"), seed("B00MFC4UGG", "www.amazon.cn"), seed("B00MFEI7RW", "www.amazon.cn")];

monitorItems.map(function(item) {
  request(item.url, function(error, response, body) {
    var $;
    if ((!error) && response.statusCode === 200) {
      $ = cheerio.load(body);
      $('#priceblock_ourprice').each(function() {
        console.log('%s', $(this).text());
      });
    }
  });
});
